# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jenkins-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: jenkins
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: jenkins
#   template:
#     metadata:
#       labels:
#         app: jenkins
#     spec:
#       containers:
#       - name: jenkins
#         image: jenkins/jenkins:lts
#         securityContext:
#           runAsUser: 0 
#         # --- ADD THIS START ---
#         env:
#           - name: GIT_CONFIG_COUNT
#             value: "1"
#           - name: GIT_CONFIG_KEY_0
#             value: "safe.directory"
#           - name: GIT_CONFIG_VALUE_0
#             value: "*"
#         # --- ADD THIS END ---
#         volumeMounts:
#         - name: jenkins-data
#           mountPath: /var/jenkins_home
#         - name: docker-sock
#           mountPath: /var/run/docker.sock
#       volumes:
#       - name: jenkins-data
#         persistentVolumeClaim:
#           claimName: jenkins-pvc
#       - name: docker-sock
#         hostPath:
#           path: /var/run/docker.sock
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins
# spec:
#   type: NodePort
#   selector:
#     app: jenkins
#   ports:
#     - port: 8080
#       targetPort: 8080
#       nodePort: 30005